import { Component, Input, Output, EventEmitter, forwardRef } from '@angular/core';
import { NgClass, NgIf, NgFor } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

export interface RadioOption {
  /** Value emitted when option is selected. */
  value: string;
  /** Visible option label. */
  label: string;
  /** Optional supporting hint under the label. */
  hint?: string;
  /** Disables this option when true. */
  disabled?: boolean;
}

@Component({
  selector: 'dsb-radio-group',
  standalone: true,
  imports: [NgClass, NgIf, NgFor],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => RadioGroupComponent),
      multi: true,
    },
  ],
  templateUrl: './radio.component.html',
  styleUrls: ['./radio.component.css'],
})
export class RadioGroupComponent implements ControlValueAccessor {
  private static idCounter = 0;

  /** Available options for the radio group. */
  @Input() options: RadioOption[] = [];
  /** Fieldset legend describing the selection. */
  @Input() legend = '';
  /** Disables the whole group. */
  @Input() disabled = false;
  /** Enables error visuals and message rendering. */
  @Input() hasError = false;
  /** Error text displayed when hasError is true. */
  @Input() errorMessage = '';
  /** Renders options horizontally when true. */
  @Input() inline = false;
  /** Native radio name attribute. Auto-generated by default. */
  @Input() groupName = `dsb-radio-${++RadioGroupComponent.idCounter}`;

  /** Emits selected value whenever selection changes. */
  @Output() valueChange = new EventEmitter<string>();

  value = '';
  onTouched: () => void = () => {};
  private onChange: (v: string) => void = () => {};

  onSelect(val: string): void {
    this.value = val;
    this.onChange(val);
    this.valueChange.emit(val);
  }

  writeValue(val: string): void { this.value = val ?? ''; }
  registerOnChange(fn: (v: string) => void): void { this.onChange = fn; }
  registerOnTouched(fn: () => void): void { this.onTouched = fn; }
  setDisabledState(disabled: boolean): void { this.disabled = disabled; }
}
