import { Component, Input, Output, EventEmitter, forwardRef } from '@angular/core';
import { NgClass, NgIf } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

export type InputSize = 'sm' | 'md' | 'lg';
export type InputType = 'text' | 'email' | 'password' | 'number' | 'search' | 'tel' | 'url';

@Component({
  selector: 'dsb-input',
  standalone: true,
  imports: [NgClass, NgIf],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => InputComponent),
      multi: true,
    },
  ],
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.css'],
})
export class InputComponent implements ControlValueAccessor {
  private static idCounter = 0;

  /** Visible label rendered above the input. */
  @Input() label = '';
  /** Native input type. */
  @Input() type: InputType = 'text';
  /** Placeholder shown when no value is present. */
  @Input() placeholder = '';
  /** Visual size variant. */
  @Input() size: InputSize = 'md';
  /** Enables error styles and aria-invalid semantics. */
  @Input() hasError = false;
  /** Error text shown when hasError is true. */
  @Input() errorMessage = '';
  /** Helper text shown when no error is active. */
  @Input() hint = '';
  /** Disables user interaction with the input. */
  @Input() disabled = false;
  /** Explicit input id for label association. Auto-generated by default. */
  @Input() inputId = `dsb-input-${++InputComponent.idCounter}`;

  /** Emits on user input with the current text value. */
  @Output() valueChange = new EventEmitter<string>();

  value = '';
  onTouched: () => void = () => {};
  private onChange: (v: string) => void = () => {};

  onInput(event: Event): void {
    const val = (event.target as HTMLInputElement).value;
    this.value = val;
    this.onChange(val);
    this.valueChange.emit(val);
  }

  writeValue(val: string): void { this.value = val ?? ''; }
  registerOnChange(fn: (v: string) => void): void { this.onChange = fn; }
  registerOnTouched(fn: () => void): void { this.onTouched = fn; }
  setDisabledState(disabled: boolean): void { this.disabled = disabled; }
}
